// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, Msg, Req } from "./chat_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.ChatReq
 */
export const ChatReq = {
  typeName: "chat.ChatReq",
  methods: {
    /**
     * @generated from rpc chat.ChatReq.ConnectServer
     */
    connectServer: {
      name: "ConnectServer",
      I: Req,
      O: Msg,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatReq.SendMsg
     */
    sendMsg: {
      name: "SendMsg",
      I: Msg,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

