// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file forum.proto (package forum, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Forum, Req } from "./forum_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service forum.ForumReq
 */
export const ForumReq = {
  typeName: "forum.ForumReq",
  methods: {
    /**
     * rpc SendMsg (Msg) returns (Empty);
     *
     * @generated from rpc forum.ForumReq.GetMsg
     */
    getMsg: {
      name: "GetMsg",
      I: Req,
      O: Forum,
      kind: MethodKind.Unary,
    },
  }
} as const;

